homepage:
    path: /
    controller: App\Controller\ArticleController::homepage

article_show:
    path: /show/{slug}
    controller: App\Controller\ArticleController::show

article_toggle_heart:
    path: /news/{slug}/heart
    controller: App\Controller\ArticleController::toggleArticleHeart

article_admin:
    path: /article/admin
    controller: App\Controller\ArticleAdminController::index

new_article:
    path: /article/admin/new
    controller: App\Controller\ArticleAdminController::new

admin_comment:
    path: /admin/comment
    controller: App\Controller\CommentAdminController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
