homepage:
    path: /
    controller: App\Controller\ArticleController::homepage

article_show:
    path: /show/{slug}
    controller: App\Controller\ArticleController::show

article_toggle_heart:
    path: /news/{slug}/heart
    controller: App\Controller\ArticleController::toggleArticleHeart

article_admin:
    path: /article/admin
    controller: App\Controller\ArticleAdminController::index

new_article:
    path: /article/admin/new
    controller: App\Controller\ArticleAdminController::new
