homepage:
    path: /
    controller: App\Controller\ArticleController::homepage

article_show:
    path: /show/{slug}
    controller: App\Controller\ArticleController::show

article_toggle_heart:
    path: /news/{slug}/heart
    controller: App\Controller\ArticleController::toggleArticleHeart

article_admin:
    path: /article/admin
    controller: App\Controller\ArticleAdminController::index

admin_article_new:
    path: /article/admin/new
    controller: App\Controller\ArticleAdminController::new

admin_comment:
    path: /admin/comment
    controller: App\Controller\CommentAdminController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_account:
    path: /account
    controller: App\Controller\AccountController::index

api_account:
    path: /api/account
    controller: App\Controller\AccountController::accountApi

app_register:
    path: /register
    controller:  App\Controller\SecurityController::register
